Repository omar2535/GraphQLer, pull requests merged in 2021-12, with the labels that each got.

#29 Finish ddos fuzzer & move to pytest
  .github/workflows/tests.yml
  .vscode/launch.json
  fengine/fuzzers/ddos_fuzzer.py
  fengine/fuzzers/defaults.py
  fengine/fuzzers/fuzzer.py
  graphqler_types/graphql_request.py
  main.py
  readme.md
  tests/fengine/fuzzers/test_ddos_fuzzer.py
  utils/grammar_parser.py
Labels: ➕enhancement

#33 add code climate enhancements
  .github/workflows/code_climate.yml
  readme.md
Labels: ➕enhancement

#35 requester implement
  fengine/fengine.py
  graphqler_types/graphql_request.py
  requester_test_temp.py
  tests/utils/__init__.py
  tests/utils/test_requester.py
  utils/requester.py
  utils/requester_test_temp.py
Labels: ➕enhancement, ❕ Critical

#36 Remove parse_depends_on
  utils/grammar_parser.py
Labels: 🐛bug

#41 Simple fuzzer
  fengine/fuzzers/constants.py
  fengine/fuzzers/ddos_fuzzer.py
  simple-fuzzer.py
  utils/requester.py
Labels: ➕enhancement

#27 edit orchestrator.py
  main.py
  utils/orchestrator.py
Labels: ➕enhancement, 🚧 WIP
